### ISSUE TITLE
has a bug 

### ISSUE THREAD

**Issue by TRAlruwaily** [NeutronX-dev/nex-scraper#2]
How i can solve this ? 

const proxies = new proxy([
                ^

TypeError: proxy is not a constructor

code:  

const proxy = require('nex-scraper');
const proxies = new proxy([
    'http://www.live-socks.net/2020/05/28-05-20-socks-5-servers.html',
    // ^^^^^^^ This Is HTML (It will get filtered)
    'https://api.proxyscrape.com/?request=getproxies&proxytype=socks5'
    // ^^^^^^^ This Is a normal API (RAW text)
]);
proxies.scrape().then(proxies => {
    // Here you can access the Proxies
    console.log(proxies)
});

**Comment by NeutronX-dev** [comment]
I have included a code that builds it. Try with
```js
const proxies = require('nex-scraper').build([
    'http://www.live-socks.net/2020/05/28-05-20-socks-5-servers.html',
    // ^^^^^^^ This Is HTML (It will get filtered)
    'https://api.proxyscrape.com/?request=getproxies&proxytype=socks5'
    // ^^^^^^^ This Is a normal API (RAW text)
]);
```
With that should work. If It does not reply to this message.
